In [35]:
import numpy as np
import torch

In [36]:
x=[
[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
[[13,14,15,16],[17,18,19,20],[21,22,23,24]]
]
x=torch.tensor(x).float()

In [37]:
x

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])

In [38]:
x.shape

torch.Size([2, 3, 4])

In [39]:
x.mean(axis=0, keepdim=True)

tensor([[[ 7.,  8.,  9., 10.],
         [11., 12., 13., 14.],
         [15., 16., 17., 18.]]])

In [40]:
x.mean(axis=0, keepdim=True).shape

torch.Size([1, 3, 4])

In [41]:
x.mean(axis=0, keepdim=False)

tensor([[ 7.,  8.,  9., 10.],
        [11., 12., 13., 14.],
        [15., 16., 17., 18.]])

In [42]:
x.mean(axis=0, keepdim=False).shape

torch.Size([3, 4])

In [43]:
x.mean(axis=1, keepdim=True)

tensor([[[ 5.,  6.,  7.,  8.]],

        [[17., 18., 19., 20.]]])

In [44]:
x.mean(axis=1, keepdim=False)

tensor([[ 5.,  6.,  7.,  8.],
        [17., 18., 19., 20.]])

In [45]:
x=torch.arange(15).view(5,3)
x = x.float()
x_mean=torch.mean(x,dim=0,keepdim=True)
x_mean0=torch.mean(x,dim=1,keepdim=True)

In [46]:
x_mean

tensor([[6., 7., 8.]])

In [47]:
x_mean0

tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.],
        [13.]])

In [48]:
x

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])

In [50]:
x.shape

torch.Size([5, 3])