In [2]:
import torch

In [2]:
# element_size():返回单个元素的字节大小。
torch.FloatTensor().element_size()

4

In [3]:
torch.ByteTensor().element_size()

1

In [9]:
# expand(*sizes):返回tensor的一个新视图，单个维度扩大为更大的尺寸。
x = torch.Tensor([[1],[2],[3]])
x.expand(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [3]:
# expand_as(tensor):将tensor扩展为参数tensor的大小
y = torch.randn(3,4)

In [4]:
x = torch.Tensor([[1],[2],[3]])

In [5]:
x.expand_as(y)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [11]:
# index_add_(dim, index, tensor):按参数index中的索引数确定的顺序，将参数tensor中的元素加到原来的tensor中。参数tensor的尺寸必须严格地与原tensor匹配，否则会发生错误。
#  - dim(int)-索引index所指向的维度 - index(LongTensor)-需要从tensor中选取的指数 - tensor(Tensor)-含有相加元素的tensor
x = torch.Tensor([[1,1,1],[1,1,1],[1,1,1]])
t = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
index = torch.LongTensor([0,2,1])
x.index_add_(0,index,t)

tensor([[ 2.,  3.,  4.],
        [ 8.,  9., 10.],
        [ 5.,  6.,  7.]])

In [16]:
# index_copy_(dim, index, tensor):按参数index中的索引数确定的顺序，将参数tensor中的元素复制到原来的tensor中。参数tensor的尺寸必须严格地与原tensor匹配，否则会发生错误。
# - dim (int)-索引index所指向的维度 - index (LongTensor)-需要从tensor中选取的指数 - tensor (Tensor)-含有被复制元素的tensor
x = torch.Tensor(3,3)
t = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
index = torch.LongTensor([0,2,1])
x.index_copy_(1,index,t)

tensor([[1., 3., 2.],
        [4., 6., 5.],
        [7., 9., 8.]])

In [18]:
# index_fill_(dim, index, val):按参数index中的索引数确定的顺序，将原tensor用参数val值填充。
#  - dim (int)-索引index所指向的维度 - index (LongTensor)-索引 - val (Tensor)-填充的值
x = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
index = torch.LongTensor([0,1])
x.index_fill(0,index,0)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [7., 8., 9.]])

In [19]:
# narrow(dimension, start, length):返回一个本tensor经过缩小后的tensor。维度dim缩小范围是start到start+length。原tensor与返回的tensor共享相同的底层内存。
# - dimension (int)-需要缩小的维度 - start (int)-起始维度 - length (int)-
x = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x.narrow(0,0,2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [20]:
x.narrow(1,1,2)

tensor([[2., 3.],
        [5., 6.],
        [8., 9.]])

In [21]:
# permute(dims):将tensor的维度换位。
x = torch.randn(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [22]:
x.permute(2,0,1).size()

torch.Size([5, 2, 3])

In [23]:
# repeat(*sizes):沿着指定的维度重复tensor。 不同于expand()，本函数复制的是tensor中的数据。
x = torch.Tensor([1,2,3])
x.repeat(4,2)

tensor([[1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.]])

In [25]:
# resize_(*sizes):将tensor的大小调整为指定的大小。如果元素个数比当前的内存大小大，就将底层存储大小调整为与新元素数目一致的大小。
# 如果元素个数比当前内存小，则底层存储不会被改变。原来tensor中被保存下来的元素将保持不变，但新内存将不会被初始化。
x = torch.Tensor([[1,2],[3,4],[5,6]])
x.resize_(2,2)

tensor([[1., 2.],
        [3., 4.]])

In [27]:
# resize_as_(tensor)：将本tensor的大小调整为与参数中的tensor相同的大小。
x = torch.Tensor([[1,2],[3,4],[5,6]])
y = torch.Tensor(2,1)
x.resize_as_(y)

tensor([[1.],
        [2.]])

In [36]:
# scatter_(input, dim, index, src):将src中的所有值按照index确定的索引写入本tensor中。其中索引是根据给定的dimension，dim按照gather()描述的规则来确定。
#  - input (Tensor)-源tensor - dim (int)-索引的轴向 - index (LongTensor)-散射元素的索引指数 - src (Tensor or float)-散射的源元素
# index的值必须是在_0_到_(self.size(dim)-1)_之间
x = torch.randn(2,5)
torch.zeros(3, 5).scatter_(0, torch.LongTensor([[0, 1, 2],[1, 2, 2]]), x)

tensor([[-0.9659,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.2145, -0.3874,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  1.8875,  1.4089,  0.0000,  0.0000]])

In [37]:
# view(*args):返回一个有相同数据但大小不同的tensor。 返回的tensor必须有与原tensor相同的数据和相同数目的元素，但可以有不同的大小。一个tensor必须是连续的contiguous()才能被查看。
x = torch.randn(4,4)
x.size()

torch.Size([4, 4])

In [38]:
y = x.view(16)

In [40]:
y.size()

torch.Size([16])

In [41]:
z = x.view(-1,8)

In [42]:
z.size()

torch.Size([2, 8])

In [43]:
# view_as(tensor):返回被视作与给定的tensor相同大小的原tensor。
z.view_as(y)

tensor([-0.1718, -1.2802,  0.3830,  0.3301, -1.0490,  1.3388,  0.4739, -1.3215,
         0.2066,  0.1110,  0.0092, -1.2016, -0.6311,  0.4724, -0.3038,  0.2829])

In [44]:
# zero_():用0填充该tensor。
x.zero_()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])