In [ ]:
import torch

In [ ]:
a = torch.randn(1,2,3,4,5)

In [ ]:
# 如果obj 是一个pytorch张量，则返回True
torch.is_tensor(a) 

In [ ]:
# 如何obj 是一个pytorch storage对象，则返回True
torch.is_storage(a) 

In [ ]:
# 返回input 张量中的元素个数
torch.numel(a) 

In [ ]:
#torch.eye(n, m=None, out=None)
#返回一个2维张量，对角线位置全1，其它位置全0
# n (int ) – 行数
# m (int, optional) – 列数.如果为None,则默认为n
# out (Tensor, optinal) - Output tensor
torch.eye(3)

In [ ]:
import numpy as np
np.array([1, 2, 3])

In [ ]:
# 将numpy.ndarray 转换为pytorch的 Tensor
torch.from_numpy(a)

In [ ]:
# 返回一个1维张量，包含在区间start 和 end 上均匀间隔的steps个点。 输出1维张量的长度为steps
torch.linspace(3, 10, steps=5)

In [ ]:
# 返回一个1维张量，包含在区间 10^start 和 10^end上以对数刻度均匀间隔的steps个点。 输出1维张量的长度为steps
torch.logspace(start=-10, end=10, steps=5)

In [ ]:
# 返回一个全为1 的张量，形状由可变参数sizes定义。
torch.ones(2, 3)

In [26]:
# 返回一个张量，包含了从区间[0,1)的均匀分布中抽取的一组随机数，形状由可变参数sizes 定义。
torch.rand(4)

tensor([0.7330, 0.5644, 0.5331, 0.3890])

In [27]:
torch.rand(2, 3)

tensor([[0.6088, 0.8211, 0.7309],
        [0.6421, 0.2705, 0.6714]])

In [29]:
# torch.randn(*sizes, out=None):返回一个张量，包含了从标准正态分布(均值为0，方差为 1，即高斯白噪声)中抽取一组随机数，形状由可变参数sizes定义。
torch.randn(4)

tensor([-0.8825, -0.4501, -0.8373, -1.1820])

In [30]:
# torch.randperm(n, out=None):给定参数n，返回一个从0 到n -1 的随机整数排列。
torch.randperm(4)

tensor([2, 1, 3, 0])

In [31]:
# torch.arange(start, end, step=1, out=None):返回一个1维张量，长度为 floor((end−start)/step)。包含从start到end，以step为步长的一组序列值(默认步长为1)。
torch.arange(1,4)

tensor([1, 2, 3])

In [32]:
torch.arange(1,2.5,0.5)

tensor([1.0000, 1.5000, 2.0000])

In [33]:
# torch.zeros(*sizes, out=None):返回一个全为标量 0 的张量，形状由可变参数sizes 定义。
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [36]:
x = torch.randn(2,3)

In [38]:
x

tensor([[ 1.0433,  1.5541,  1.1989],
        [ 0.1640,  0.9720, -0.2798]])

In [39]:
# torch.cat(inputs, dimension=0):在给定维度上对输入的张量序列seq 进行连接操作。
torch.cat((x,x,x),0)

tensor([[ 1.0433,  1.5541,  1.1989],
        [ 0.1640,  0.9720, -0.2798],
        [ 1.0433,  1.5541,  1.1989],
        [ 0.1640,  0.9720, -0.2798],
        [ 1.0433,  1.5541,  1.1989],
        [ 0.1640,  0.9720, -0.2798]])

In [40]:
torch.cat((x,x,x),1)

tensor([[ 1.0433,  1.5541,  1.1989,  1.0433,  1.5541,  1.1989,  1.0433,  1.5541,
          1.1989],
        [ 0.1640,  0.9720, -0.2798,  0.1640,  0.9720, -0.2798,  0.1640,  0.9720,
         -0.2798]])

In [53]:
# torch.chunk(tensor, chunks, dim=0):在给定维度(轴)上将输入张量进行分块儿。
# chunks (int) – 分块的个数
torch.chunk(x,2,dim=1)

(tensor([[1.0433, 1.5541],
         [0.1640, 0.9720]]),
 tensor([[ 1.1989],
         [-0.2798]]))

In [61]:
# torch.gather(input, dim, index, out=None):沿给定轴dim，将输入索引张量index指定位置的值进行聚合。
t = torch.Tensor([[1,2],[3,4]])
torch.gather(t, 1, torch.LongTensor([[0,0],[1,0]]))

tensor([[1., 1.],
        [4., 3.]])

In [62]:
# torch.index_select(input, dim, index, out=None):沿着指定维度对输入进行切片，取index中指定的相应项(index为一个LongTensor)，然后返回到一个新的张量， 返回的张量与原始张量_Tensor_有相同的维度(在指定轴上)。
x = torch.randn(3, 4)
indices = torch.LongTensor([0, 2])
torch.index_select(x, 0, indices)

tensor([[-0.1726,  1.0630, -0.2360, -0.5979],
        [-1.4415,  0.6008, -0.1244,  0.0935]])

In [63]:
torch.index_select(x, 1, indices)

tensor([[-0.1726, -0.2360],
        [ 1.4059, -1.4732],
        [-1.4415, -0.1244]])

In [64]:
# torch.masked_select(input, mask, out=None):根据掩码张量mask中的二元值，取输入张量中的指定项( mask为一个 ByteTensor)，将取值返回到一个新的1D张量，
# 张量 mask须跟input张量有相同数量的元素数目，但形状或维度不需要相同。 注意： 返回的张量不与原始张量共享内存空间。
x = torch.randn(3,4)
torch.masked_select(x, x<0.1)

tensor([-0.6187, -1.0193, -0.2069])