In [4]:
import torch
from torch.autograd import Variable
from torch.nn import functional as F

In [5]:
# torch.nn.functional.conv1d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)
# 对几个输入平面组成的输入信号应用1D卷积。
fliters = Variable(torch.randn(33,16,3))
inputs = Variable(torch.randn(20,16,50))
F.conv1d(inputs,fliters)

tensor([[[ -3.1624,   5.8284,   8.0172,  ...,   4.7769,   6.4400,   6.3647],
         [  2.1417,  -1.7755,  -6.4943,  ...,   6.7356,   0.0291,  -3.5957],
         [  2.5677,   3.5388,   0.1226,  ...,  -7.9781,   2.1954,  -8.6682],
         ...,
         [ -7.0087,   4.2625,  -0.9824,  ...,   0.2429,  -3.8899,   2.4892],
         [  4.6992,   1.1544,   2.5803,  ...,   2.7860,   2.7565,  -3.3417],
         [  7.9844,  11.4087,   2.1051,  ...,   3.4665,  -1.1725,  -8.7679]],

        [[-13.1558,  -8.1435, -13.9676,  ...,  -5.9412,   4.7365,  -1.6542],
         [  0.5278,  -0.9536,  -0.2248,  ...,  -9.4538,  12.2925,   2.9705],
         [ -9.0265,   4.6353, -10.9682,  ...,  -0.7032,  -4.5731,   2.2254],
         ...,
         [-11.6344, -22.0302,  13.4817,  ...,   0.9229, -11.3428,   3.5999],
         [-10.2158,  -7.3159,  -5.3098,  ...,  -1.8188,   2.1642,   0.6675],
         [  0.5082,  -1.2744,   1.7287,  ..., -15.0612,   0.4982,   1.3467]],

        [[ 13.1014,  -4.2809,   0.6176,  ...

In [7]:
# torch.nn.functional.conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)
# 对几个输入平面组成的输入信号应用2D卷积。
filters = Variable(torch.randn(8,4,3,3))
inputs = Variable(torch.randn(1,4,5,5))
F.conv2d(inputs, filters, padding=1)

tensor([[[[ -7.6366,   1.5845,  -0.5984,  -4.4532,  -2.5032],
          [ -1.4687,   0.2171,  -6.5862,  -0.6658,  -5.1287],
          [  6.5757,   7.3364,   3.2489,  -2.9147,   8.7382],
          [  6.6041,   2.9069,  -4.6230,   3.7042,  -4.6457],
          [ -1.8336,   1.0205,  -2.1020,  -2.6842,  -1.2131]],

         [[  5.1350,   5.8458,  -6.6952,  -2.9227,   2.5235],
          [ -7.7761,  -0.8859,  -3.6880,  -4.8251,   1.9459],
          [  0.6416,   0.2382, -13.4336,  -3.8464,  -0.8379],
          [  0.2105,  -9.7487,   6.1228,  -4.4833,   6.8832],
          [  3.6496,  10.8748, -12.9969,   7.6911,   1.8598]],

         [[ -0.3487,  -8.5946,  -0.8449,  -0.1845,  -0.1193],
          [  1.9774,  -7.3834,   2.2845, -10.0923,   2.7557],
          [  1.5404,   1.3552,  -4.1357,   3.4619,  -4.7273],
          [  7.7184,  -1.5409,   6.7549,  -7.3993,   5.0917],
          [  6.6635,  -0.1140,   5.6164,  -7.8549,   5.3558]],

         [[ -1.7561,  -2.3363,   6.8524,   0.6251,   2.2231],
  

In [8]:
# torch.nn.functional.avg_pool1d(input, kernel_size, stride=None, padding=0, ceil_mode=False, count_include_pad=True)
# 对由几个输入平面组成的输入信号进行一维平均池化。
input = Variable(torch.Tensor([[[1,2,3,4,5,6,7]]]))
F.avg_pool1d(input, kernel_size=3, stride=2)

tensor([[[2., 4., 6.]]])

In [9]:
# torch.nn.functional.avg_pool2d(input, kernel_size, stride=None, padding=0, ceil_mode=False, count_include_pad=True)
# 在kh x kw区域中应用步长为dh x dw的二维平均池化操作。输出特征的数量等于输入平面的数量。

In [10]:
# torch.nn.functional.max_pool1d(input, kernel_size, stride=None, padding=0, dilation=1, ceil_mode=False, return_indices=False)
# torch.nn.functional.max_pool2d(input, kernel_size, stride=None, padding=0, dilation=1, ceil_mode=False, return_indices=False)

In [11]:
from torch import autograd

In [12]:
# torch.autograd.Variable
# 包装一个Tensor,并记录用在它身上的operations。

In [ ]:
# forward(* input)
# 执行operation。