In [1]:
# numpy中的数组
import numpy as np

In [3]:
np.array([1, 2, 3, 4, 5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [4]:
# 多维数组
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
# 创建一个长度为10的数组，数组的值都是0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# 创建一个3×5的浮点型数组，数组的值都是1 
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# 创建一个3×5的浮点型数组，数组的值都是3.14 
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
# 创建一个3×5的浮点型数组，数组的值是一个线性序列 
# 从0开始，到20结束，步长为2 
# （它和内置的range()函数类似） 
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# 创建一个5个元素的数组，这5个数均匀地分配到0~1 
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
# 创建一个3×3的、在0~1均匀分布的随机数组成的数组 
np.random.random((3, 3))

array([[0.37006708, 0.8752662 , 0.94625525],
       [0.46482557, 0.37692518, 0.67969341],
       [0.92801894, 0.47930538, 0.237357  ]])

In [11]:
# 创建一个3×3的、均值为0、方差为1的 
# 正态分布的随机数数组 
np.random.normal(0, 1, (3, 3))

array([[ 0.2914134 , -0.45412656,  1.42498635],
       [ 1.30775257, -0.87339581, -0.01895686],
       [-0.0071233 ,  0.64148477, -0.45803593]])

In [12]:
# 创建一个3×3的、[0, 10)区间的随机整型数组 
np.random.randint(0, 10, (3, 3))

array([[8, 7, 0],
       [6, 1, 7],
       [5, 2, 7]])

In [13]:
 # 创建一个3×3的单位矩阵 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# 创建一个由3个整型数组成的未初始化的数组 
# 数组的值是内存空间中的任意值 
np.empty(3)

array([1., 1., 1.])

array([1.13622787e-311, 9.58487353e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.16097020e-028, 6.37112413e-067, 6.36791070e-062,
       1.31306916e-071, 5.01163173e+217, 8.37170074e-144, 2.44698565e-056,
       1.16188684e+165, 7.17693131e-091, 8.60608144e-043, 5.01163190e+217,
       5.49419094e-143, 9.80058441e+252, 7.50189709e+247, 1.35617292e+248,
       5.08419390e-066, 3.57233717e-062, 5.45392842e-066, 3.27044095e+179,
       1.63365440e+185, 5.04621361e+180, 8.37170571e-144, 9.30350598e+199,
       5.60230216e-067, 1.58268989e-319])

In [24]:
# 指定数据类型
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [25]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [26]:
# 数组的一些属性
np.random.seed(0) # 设置随机数种子 
x1 = np.random.randint(10, size=6) # 一维数组 
x2 = np.random.randint(10, size=(3, 4)) # 二维数组 
x3 = np.random.randint(10, size=(3, 4, 5)) # 三维数组

In [27]:
x3.ndim # 查看数组的维度

3

In [28]:
x3.shape # 数组每个维度的大小

(3, 4, 5)

In [29]:
x3.size # 数组的总大小

60

In [30]:
x3.dtype # 数组的数据类型

dtype('int32')

In [31]:
x3.itemsize # 每个数组元素字节大小

4

In [32]:
x3.nbytes # 数组总字节大小的属性

240

In [33]:
# 数组索引：获取单个元素
x1

array([5, 0, 3, 3, 7, 9])

In [34]:
x1[0]

5

In [35]:
x1[-1]

9

In [36]:
 x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [37]:
x2[0, 0] # 查看多维数组

3

In [38]:
x2[2, -1]

7

In [39]:
x2[0, 0] = 12 # 修改元素

In [40]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [41]:
x1[0] = 3.1315926

In [42]:
x1

array([3, 0, 3, 3, 7, 9])

In [43]:
# 数组切片：获取子数组
# x[start:stop:step]
x = np.arange(10)

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x[:5] # 前五个元素

array([0, 1, 2, 3, 4])

In [46]:
x[5:] # 索引五之后的元素

array([5, 6, 7, 8, 9])

In [47]:
x[4:7] # 中间的子数组

array([4, 5, 6])

In [48]:
x[::2] # 每隔一个元素

array([0, 2, 4, 6, 8])

In [49]:
x[1::2] # 每隔一个元素，从索引1开始

array([1, 3, 5, 7, 9])

In [50]:
x[::-1] # 所有元素，逆序的

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [51]:
x[5::-2] # 从索引5开始每隔一个元素逆序

array([5, 3, 1])

In [52]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [53]:
x2[:2, :3] # 两行，三列

array([[12,  5,  2],
       [ 7,  6,  8]])

In [54]:
x2[:3, ::2] # 所有行，每隔一列

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [55]:
 x2[::-1, ::-1] # 子数组维度也可以同时被逆序

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [57]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [56]:
print(x2[:, 0]) # x2的第一列

[12  7  1]


In [58]:
 print(x2[0, :]) # x2的第一行

[12  5  2  4]


In [59]:
print(x2[0]) #等于x2[0, :]

[12  5  2  4]


In [61]:
# 数组切片返回的是 数组数据的视图，而不是数值数据的副本。
x2_sub = x2[:2, :2]

In [62]:
x2_sub

array([[12,  5],
       [ 7,  6]])

In [63]:
x2_sub[0, 0] = 99

In [66]:
x2_sub

array([[99,  5],
       [ 7,  6]])

In [65]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [67]:
# 创建数组的副本
x2_sub_copy = x2[:2, :2].copy()

In [69]:
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [70]:
x2_sub_copy[0, 0] = 42

In [71]:
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [72]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [73]:
# 数组的变形
grid = np.arange(1, 10).reshape((3, 3))

In [74]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
x = np.array([1, 2, 3])

In [76]:
x

array([1, 2, 3])

In [77]:
x.reshape((1, 3)) # 通过变形获得的行向量 

array([[1, 2, 3]])

In [78]:
 x[np.newaxis, :] # 通过newaxis获得的行向量

array([[1, 2, 3]])

In [79]:
x.reshape((3, 1)) # 通过变形获得的列向量 

array([[1],
       [2],
       [3]])

In [80]:
x[:, np.newaxis] # 通过newaxis获得的列向量 

array([[1],
       [2],
       [3]])

In [81]:
# 数组的拼接和分裂
x = np.array([1, 2, 3]) 
y = np.array([3, 2, 1]) 
np.concatenate([x, y]) # np.concatenate 将数组元组或数组列表作为第一个参数

array([1, 2, 3, 3, 2, 1])

In [82]:
z = [99, 99, 99] 
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [83]:
# np.concatenate 也可以用于二维数组的拼接
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [84]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.concatenate([grid, grid]) # 沿着第一个轴拼接 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [86]:
np.concatenate([grid, grid], axis=1) # 沿着第二个轴拼接（从0开始索引）

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [87]:
x = np.array([1, 2, 3]) 
grid = np.array([[9, 8, 7], [6, 5, 4]]) 
np.vstack([x, grid]) # 垂直栈数组 

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [89]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [88]:
y = np.array([[99], [99]]) 
np.hstack([grid, y])  # 水平栈数组

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [90]:
# 数组的分裂
x = [1, 2, 3, 99, 99, 3, 2, 1] 
x1, x2, x3 = np.split(x, [3, 5]) # N 分裂点会得到 N + 1 个子数组

In [92]:
x1, x2, x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [96]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
upper, lower = np.vsplit(grid, [2])

In [95]:
upper, lower

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [97]:
left, right = np.hsplit(grid, [2])

In [98]:
left, right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [99]:
# 广播
a = np.array([0, 1, 2]) 
b = np.array([5, 5, 5]) 
a + b

array([5, 6, 7])

In [100]:
a + 5

array([5, 6, 7])

In [101]:
M = np.ones((3, 3))

In [102]:
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [104]:
a = np.arange(3) 
b = np.arange(3)[:, np.newaxis]

In [105]:
a,b

(array([0, 1, 2]),
 array([[0],
        [1],
        [2]]))

In [106]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [107]:
# 规则 1：如果两个数组的维度数不相同，那么小维度数组的形状将 会在最左边补 1。 
# M.shape -> (2, 3) a.shape -> (1, 3)
# 规则 2：如果两个数组的形状在任何一个维度上都不匹配，那么数 组的形状会沿着维度为 1 的维度扩展以匹配另外一个数组的形状。 
# M.shape -> (2, 3) a.shape -> (2, 3)
# 规则 3：如果两个数组的形状在任何一个维度上都不匹配并且没有 任何一个维度等于 1，那么会引发异常。
M = np.ones((2, 3)) 
a = np.arange(3)

In [109]:
M,a

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 1, 2]))

In [110]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [111]:
a = np.arange(3).reshape((3, 1)) 
b = np.arange(3)

In [112]:
a,b

(array([[0],
        [1],
        [2]]),
 array([0, 1, 2]))

In [113]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [114]:
M = np.ones((3, 2)) 
a = np.arange(3)

In [115]:
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [116]:
a

array([0, 1, 2])

In [117]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [118]:
a[:, np.newaxis].shape

(3, 1)

In [119]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])