In [1]:
import numpy as np
# 比较操作

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
np.equal(x, 3)

array([False, False,  True, False, False])

In [4]:
np.not_equal(x, 3)

array([ True,  True, False,  True,  True])

In [5]:
np.less(x, 3)

array([ True,  True, False, False, False])

In [7]:
np.less_equal(x, 3)

array([ True,  True,  True, False, False])

In [8]:
np.greater(x, 3)

array([False, False, False,  True,  True])

In [9]:
np.greater_equal(x, 3)

array([False, False,  True,  True,  True])

In [10]:
# 操作布尔数组
rng = np.random.RandomState(0) 
x = rng.randint(10, size=(3, 4))

In [11]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [12]:
np.count_nonzero(x < 6) # np.count_nonzero:统计布尔数组中 True 记录的个数

8

In [13]:
np.sum(x < 6)

8

In [14]:
np.sum(x < 6, axis=1) # 每行有多少值小于6？

array([4, 2, 2])

In [15]:
np.any(x > 8) # 有没有值大于8？

True

In [16]:
np.any(x < 0) # 有没有值小于0？ 

False

In [17]:
np.all(x < 10) # 是否所有值都小于10？ 

True

In [18]:
np.all(x == 6) # 是否所有值都等于6？ 

False

In [19]:
np.all(x < 8, axis=1) # 是否每行的所有值都小于8？

array([ True, False,  True])

In [22]:
# 花哨的索引
rand = np.random.RandomState(42) 
x = rand.randint(100, size=10)

In [23]:
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [24]:
ind = [3, 7, 4]

In [25]:
x[ind]

array([71, 86, 60])

In [26]:
ind = np.array([[3, 7], [4, 5]])

In [27]:
x[ind]

array([[71, 86],
       [60, 20]])

In [28]:
# 多维数组
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
row = np.array([0, 1, 2]) 
col = np.array([2, 1, 3]) 
X[row, col]

array([ 2,  5, 11])

In [30]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [31]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [32]:
row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

In [33]:
# 组合索引
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
X[2, [2, 0, 1]]

array([10,  8,  9])

In [35]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [36]:
mask = np.array([1, 0, 1, 0], dtype=bool) 
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [39]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [40]:
# 数组的排序
x = np.array([2, 1, 4, 3, 5]) 
np.sort(x)

array([1, 2, 3, 4, 5])

In [42]:
x.sort()

In [43]:
x

array([1, 2, 3, 4, 5])

In [44]:
x = np.array([2, 1, 4, 3, 5]) 
i = np.argsort(x) # 原始数组排好序的索引值
i

array([1, 0, 3, 2, 4], dtype=int64)

In [45]:
x[i]

array([1, 2, 3, 4, 5])

In [46]:
rand = np.random.RandomState(42) 
X = rand.randint(0, 10, (4, 6))

In [47]:
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [48]:
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [49]:
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [62]:
# 部分排序：分隔
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3) # np.partition函数的输入是数组和数字 K，输出结果是一个新数组，最左边是第 K 小的 值，往右是任意顺序的其他值

array([2, 1, 3, 4, 6, 5, 7])

In [82]:
np.partition(X, 4, axis=1)

array([[6, 6, 3, 4, 7, 9],
       [3, 2, 6, 4, 7, 7],
       [1, 5, 2, 4, 7, 7],
       [0, 4, 1, 5, 5, 9]])

In [83]:
# numpy的结构化数组
name = ['Alice', 'Bob', 'Cathy', 'Doug'] 
age = [25, 45, 37, 19] 
weight = [55.0, 85.5, 68.0, 61.5]

In [84]:
# 使用复合数据结构的结构化数组
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'), 'formats':('U10', 'i4', 'f8')})
#  U10 表示“长度不超过 10 的 Unicode 字符串”，i4 表示“4 字节（即 32 比特）整型”，f8 表示“8 字节（即 64 比特）浮点型”。

In [85]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [86]:
data['name'] = name 
data['age'] = age 
data['weight'] = weight

In [86]:
data

array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [87]:
data['name'] # 获取所有名字

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [88]:
data[0] # 获取数据第一行

('Alice', 25, 55.)

In [89]:
data[-1]['name']#获取最后一行的名字

'Doug'

In [90]:
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [91]:
# 生成结构化数组
np.dtype({'names':('name', 'age', 'weight'), 'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [92]:
np.dtype({'names':('name', 'age', 'weight'), 'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [93]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [94]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [95]:
# 记录数组：结构化数组的扭转
data['age']

array([25, 45, 37, 19])

In [96]:
data_rec = data.view(np.recarray) # 域可以像属性一样获取

In [97]:
data_rec.age

array([25, 45, 37, 19])